### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [asaaki/capture-the-ip#6]

**Comment by asaaki** [comment]
I have to check the logic again, because I do have to consider some other means of getting an IPv4 while being behind some level of proxy/gateway.

The service is currently running on fly.io, so there are some layers in front of it and in the specific setup I cannot always rely on the client IP, as for some requesters this would be a fly.io internal IP (people coming from IPv6 are quite the usual suspects, but there might be other reasons why the client IP is just an internal one).

So it's quite tricky to provide both a fair game and prevent too easy hacking/cheating.

---

Edit: mostly it's just a bit of fly.io-annoyance (kind of forcing you to also set up IPv6 for proper domain configuration), other hosting environments might make it easier on me.

**Comment by asaaki** [comment]
So, since I plan to continue using fly.io and they actually do provide me with a client IP, which just may or may not be IPv4, I decided to remove all other means of IP extraction. IPv6 is not supported as intended and thus also overriding/faking it with forward headers is not allowed anymore.

Thanks for reminding me about this issue. ❤️
